<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class Password extends Constraint
{
    /*
     * Any public properties become valid options for the annotation.
     * Then, use these in your validator class.
     */
    public $message = 'Votre mot de passe n\'est pas identique';

    public function getTargets()
    {
        return parent::CLASS_CONSTRAINT; // TODO: Change the autogenerated stub
    }


}
